/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;


/**
 *
 * @author Sergio-PC
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    String palabraOculta = "GANSO";
    
    int numeroFallos = 0;
    
    
    
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {

        
        initComponents();
        
        
        //dibuja la imagen del ahorcado sin fallos
        dibujaImagen(0);
    }

    private void dibujaImagen(int numeroFallos){
       ImageIcon miImagen = null;
       URL nombreImagen = null;
       int ancho = panelAhorcado.getWidth();
       int alto = panelAhorcado.getHeight();
       
       switch(numeroFallos){
           case 0: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_0.png")); break;
           case 1: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_1.png")); break;
           case 2: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_2.png")); break;
           case 3: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_3.png")); break;
           case 4: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_4.png")); break;
           case 5: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_5.png")); break;
           default: nombreImagen = (getClass().getResource("/Imagenes/ahorcado_fin.png")); break;
           
       }
           
       
            
       miImagen = new ImageIcon(new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
           
        
       panelAhorcado.setIcon(miImagen);
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        panelAhorcado = new javax.swing.JLabel();
        BotonA = new javax.swing.JButton();
        BotonB = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();
        BotonD = new javax.swing.JButton();
        BotonE = new javax.swing.JButton();
        BotonF = new javax.swing.JButton();
        BotonG = new javax.swing.JButton();
        BotonH = new javax.swing.JButton();
        BotonI = new javax.swing.JButton();
        BotonJ = new javax.swing.JButton();
        BotonK = new javax.swing.JButton();
        BotonL = new javax.swing.JButton();
        BotonM = new javax.swing.JButton();
        BotonN = new javax.swing.JButton();
        BotonÑ = new javax.swing.JButton();
        BotonO = new javax.swing.JButton();
        BotonP = new javax.swing.JButton();
        BotonQ = new javax.swing.JButton();
        BotonR = new javax.swing.JButton();
        BotonS = new javax.swing.JButton();
        BotonT = new javax.swing.JButton();
        BotonU = new javax.swing.JButton();
        BotonV = new javax.swing.JButton();
        BotonW = new javax.swing.JButton();
        Boton = new javax.swing.JButton();
        BotonX = new javax.swing.JButton();
        BotonY = new javax.swing.JButton();
        BotonZ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pantalla.setText("_ _ _ _ _ ");

        panelAhorcado.setText("panelAhorcado");

        BotonA.setText("A");
        BotonA.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonAMousePressed(evt);
            }
        });
        BotonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAActionPerformed(evt);
            }
        });

        BotonB.setText("B");
        BotonB.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonBMousePressed(evt);
            }
        });
        BotonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBActionPerformed(evt);
            }
        });

        BotonC.setText("C");
        BotonC.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonCMousePressed(evt);
            }
        });
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });

        BotonD.setText("D");
        BotonD.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonDMousePressed(evt);
            }
        });
        BotonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDActionPerformed(evt);
            }
        });

        BotonE.setText("E");
        BotonE.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonEMousePressed(evt);
            }
        });
        BotonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEActionPerformed(evt);
            }
        });

        BotonF.setText("F");
        BotonF.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonFMousePressed(evt);
            }
        });
        BotonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFActionPerformed(evt);
            }
        });

        BotonG.setText("G");
        BotonG.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonGMousePressed(evt);
            }
        });

        BotonH.setText("H");
        BotonH.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonHMousePressed(evt);
            }
        });

        BotonI.setText("I");
        BotonI.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonIMousePressed(evt);
            }
        });
        BotonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIActionPerformed(evt);
            }
        });

        BotonJ.setText("J");
        BotonJ.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonJMousePressed(evt);
            }
        });
        BotonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonJActionPerformed(evt);
            }
        });

        BotonK.setText("K");
        BotonK.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonKMousePressed(evt);
            }
        });
        BotonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonKActionPerformed(evt);
            }
        });

        BotonL.setText("L");
        BotonL.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonLMousePressed(evt);
            }
        });
        BotonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLActionPerformed(evt);
            }
        });

        BotonM.setText("M");
        BotonM.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonMMousePressed(evt);
            }
        });
        BotonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMActionPerformed(evt);
            }
        });

        BotonN.setText("N");
        BotonN.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonNMousePressed(evt);
            }
        });
        BotonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNActionPerformed(evt);
            }
        });

        BotonÑ.setText("Ñ");
        BotonÑ.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonÑ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonÑMousePressed(evt);
            }
        });

        BotonO.setText("O");
        BotonO.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonOMousePressed(evt);
            }
        });
        BotonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOActionPerformed(evt);
            }
        });

        BotonP.setText("P");
        BotonP.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonPMousePressed(evt);
            }
        });
        BotonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPActionPerformed(evt);
            }
        });

        BotonQ.setText("Q");
        BotonQ.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonQMousePressed(evt);
            }
        });
        BotonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQActionPerformed(evt);
            }
        });

        BotonR.setText("R");
        BotonR.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonRMousePressed(evt);
            }
        });
        BotonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRActionPerformed(evt);
            }
        });

        BotonS.setText("S");
        BotonS.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonSMousePressed(evt);
            }
        });
        BotonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSActionPerformed(evt);
            }
        });

        BotonT.setText("T");
        BotonT.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonTMousePressed(evt);
            }
        });

        BotonU.setText("U");
        BotonU.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonUMousePressed(evt);
            }
        });

        BotonV.setText("V");
        BotonV.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonVMousePressed(evt);
            }
        });
        BotonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVActionPerformed(evt);
            }
        });

        BotonW.setText("W");
        BotonW.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonWMousePressed(evt);
            }
        });
        BotonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonWActionPerformed(evt);
            }
        });

        Boton.setPreferredSize(new java.awt.Dimension(42, 42));
        Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonMousePressed(evt);
            }
        });
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        BotonX.setText("X");
        BotonX.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonXMousePressed(evt);
            }
        });
        BotonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonXActionPerformed(evt);
            }
        });

        BotonY.setText("Y");
        BotonY.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonYMousePressed(evt);
            }
        });
        BotonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonYActionPerformed(evt);
            }
        });

        BotonZ.setText("Z");
        BotonZ.setPreferredSize(new java.awt.Dimension(42, 42));
        BotonZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonZMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BotonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BotonU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonW, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(BotonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BotonT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(BotonB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(BotonG, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BotonA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonG, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonK, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonÑ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonW, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonCActionPerformed

    private void BotonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonDActionPerformed

    private void BotonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonEActionPerformed

    private void BotonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonBActionPerformed

    private void BotonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonFActionPerformed

    private void BotonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonLActionPerformed

    private void BotonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonKActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonKActionPerformed

    private void BotonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonMActionPerformed

    private void BotonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonJActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonJActionPerformed

    private void BotonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonIActionPerformed

    private void BotonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonRActionPerformed

    private void BotonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonXActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonXActionPerformed

    private void BotonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonQActionPerformed

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonActionPerformed

    private void BotonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonYActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonYActionPerformed

    private void BotonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonWActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonWActionPerformed

    private void BotonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonVActionPerformed

    private void BotonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonSActionPerformed

    private void BotonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonPActionPerformed

    private void BotonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonOActionPerformed

    private void BotonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonAActionPerformed

    private void BotonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonNActionPerformed

    
    
    
    
    private void chequeaLetra(String letra){
       letra = letra.toUpperCase(); //lo convierte en mayuscula
        //String palabraConGuiones = pantalla.getText();
        StringBuilder palabraConGuiones = new StringBuilder(pantalla.getText());
        if(palabraOculta.contains(letra)){
            for (int i=0; i < palabraOculta.length(); i++){
                if(palabraOculta.charAt(i) == letra.charAt(0)){
                   palabraConGuiones.setCharAt(2*i, letra.charAt(0));
                    
                }
            }
            pantalla.setText(palabraConGuiones.toString());
        }
        else  
        numeroFallos++;
        dibujaImagen(numeroFallos);
    }
        
                       // palabraConGuiones = palabraConGuiones.substring(0,2*i)
                         //             + letra 
                           //           + palabraConGuiones.substring(2*i+1);
    
    private void chequeaBoton( JButton miBoton){
        miBoton.setEnabled(false);
        chequeaLetra(miBoton.getText());
    }
    
    
    private void BotonAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonAMousePressed

    private void BotonBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonBMousePressed

    private void BotonCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonCMousePressed

    private void BotonDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonDMousePressed

    private void BotonEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonEMousePressed

    private void BotonFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonFMousePressed

    private void BotonGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonGMousePressed

    private void BotonHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonHMousePressed

    private void BotonIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonIMousePressed

    private void BotonJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonJMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonJMousePressed

    private void BotonKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonKMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonKMousePressed

    private void BotonLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonLMousePressed

    private void BotonMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonMMousePressed

    private void BotonNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonNMousePressed

    private void BotonÑMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonÑMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonÑMousePressed

    private void BotonOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonOMousePressed

    private void BotonPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonPMousePressed

    private void BotonQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonQMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonQMousePressed

    private void BotonRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonRMousePressed

    private void BotonSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonSMousePressed

    private void BotonTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonTMousePressed

    private void BotonUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonUMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonUMousePressed

    private void BotonVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonVMousePressed

    private void BotonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonWMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonWMousePressed

    private void BotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonMousePressed

    private void BotonXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonXMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonXMousePressed

    private void BotonYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonYMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonYMousePressed

    private void BotonZMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonZMousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_BotonZMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton;
    private javax.swing.JButton BotonA;
    private javax.swing.JButton BotonB;
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonD;
    private javax.swing.JButton BotonE;
    private javax.swing.JButton BotonF;
    private javax.swing.JButton BotonG;
    private javax.swing.JButton BotonH;
    private javax.swing.JButton BotonI;
    private javax.swing.JButton BotonJ;
    private javax.swing.JButton BotonK;
    private javax.swing.JButton BotonL;
    private javax.swing.JButton BotonM;
    private javax.swing.JButton BotonN;
    private javax.swing.JButton BotonO;
    private javax.swing.JButton BotonP;
    private javax.swing.JButton BotonQ;
    private javax.swing.JButton BotonR;
    private javax.swing.JButton BotonS;
    private javax.swing.JButton BotonT;
    private javax.swing.JButton BotonU;
    private javax.swing.JButton BotonV;
    private javax.swing.JButton BotonW;
    private javax.swing.JButton BotonX;
    private javax.swing.JButton BotonY;
    private javax.swing.JButton BotonZ;
    private javax.swing.JButton BotonÑ;
    private javax.swing.JLabel panelAhorcado;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
